/* DEFINE_COMMAND(id, fn, index) */
DEFINE_COMMAND(COMMAND_THREE, command_three, 3)
DEFINE_COMMAND(COMMAND_FOUR, command_four, 4)
DEFINE_COMMAND(COMMAND_ONE, command_one, 1)
DEFINE_COMMAND(COMMAND_ZERO, command_zero, 0)
DEFINE_COMMAND(COMMAND_TWO, command_two, 2)
